apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: meta-spa
  name: meta-spa
spec:
  clusterIP: 172.30.225.102
  clusterIPs:
  - 172.30.225.102
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: meta-spa
  sessionAffinity: None
  type: ClusterIP
