name: Create envfile

on:
  push:
    branches:
      - master
jobs: 
  create_env_file_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_TEST_ENV: ${{ secrets.TEST_ENV }}
          ENV_TEST_ENV_TWO: 'por favor andaaaaa'
