name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to OCI
        uses: docker/login-action@v3
        with:
          registry: iad.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: iad.ocir.io/idwwmbyiyhww/meta-spa:latest
          build-args: |
            VITE_MS_AUTH_API_URL=${{ secrets.VITE_MS_AUTH_API_URL }} 
            VITE_MS_ORGANIZATION_API_URL=${{ secrets.VITE_MS_ORGANIZATION_API_URL }} 
            VITE_MS_PROCESSES_API_URL=${{ secrets.VITE_MS_PROCESSES_API_URL }} 
            VITE_MS_PROJECTS_API_URL=${{ secrets.VITE_MS_PROJECTS_API_URL }}
            VITE_MS_SURVEYS_API_URL=${{ secrets.VITE_MS_SURVEYS_API_URL }}

