name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_MS_AUTH_API_URL: "https://ms-auth-meta-ms.apps.ocp01.sbox.fusion.com.ar"
          envkey_VITE_MS_PROJECTS_API_URL: "https://ms-projects-meta-ms.apps.ocp01.sbox.fusion.com.ar"
          envkey_VITE_MS_PROCESSES_API_URL: "https://ms-process-meta-ms.apps.ocp01.sbox.fusion.com.ar" 
          envkey_VITE_MS_ORGANIZATION_API_URL: "https://ms-organization-meta-ms.apps.ocp01.sbox.fusion.com.ar" 
          envkey_VITE_MS_SURVEYS_API_URL: "https://ms-surveys-meta-ms.apps.ocp01.sbox.fusion.com.ar"
          file_name: .env
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/meta-spa:latest
